name: felicidade
description: "Felicidade"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.0
  http: ^0.13.4
  connectivity: ^3.0.6
  dropdown_button2: ^2.3.9
  flutter_svg: ^1.1.5
  intl: ^0.17.0
  modal_progress_hud_nsn: ^0.5.1
  fluttertoast: ^8.0.9
  cached_network_image: ^3.3.0
  image_picker: ^1.0.7
  image_cropper: ^3.0.1
  dio: ^4.0.6
  flutter_screenutil: ^5.9.3
  get_it: ^7.2.0
  persistent_bottom_nav_bar_v2: ^4.2.6
  shared_preferences: ^2.0.11
  carousel_slider: ^4.2.1
  permission_handler: ^10.2.0
  dropdown_search: ^3.0.0
  url_launcher: ^6.1.14
  fl_chart: ^0.64.0
  webview_flutter: ^3.0.0
  readmore: ^2.2.0
  flutter_custom_dialog: ^1.3.0
  slidable_button: ^3.0.0+1
  qr_code_scanner: ^1.0.1
  geolocator: ^11.0.0
  loading_animation_widget: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

