name: felicidade
description: "Felicidade"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <=3.6.1"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.5
  get_it: ^7.2.0
#  connectivity: ^3.0.6
  flutter_svg: ^2.0.5
  shimmer: ^3.0.0
  extended_image: ^9.1.0
  intl: ^0.20.2
  fluttertoast: ^8.0.9
  image_picker: ^1.0.7
  dio: ^5.0.2
  flutter_screenutil: ^5.9.3
  persistent_bottom_nav_bar_v2: ^5.3.1
  shared_preferences: ^2.0.11
  flutter_secure_storage: ^9.2.4
  modal_progress_hud_nsn: ^0.5.1
  synchronized: ^3.1.0
  win32: ^5.5.4
  url_launcher: ^6.1.14


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/pngIcons/
    - assets/icons/svgIcons/


  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/font/Satoshi-Light.otf
          weight: 300
        - asset: assets/font/Satoshi-Medium.otf
          weight: 500
        - asset: assets/font/Satoshi-Bold.otf
          weight: 700

    - family: Ogg
      fonts:
        - asset: assets/font/OggText-Light.otf
          weight: 300
        - asset: assets/font/Ogg-Regular.otf
          weight: 400
        - asset: assets/font/OggText-Medium.otf
          weight: 500
        - asset: assets/font/Ogg-Bold.otf
          weight: 700
